---
language: rust
sudo: false

matrix:
  include:
    # Minimum rustc version
    - rust: 1.21.0
    - rust: nightly

script:
  - cargo test --all
  - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench --all; fi'
  - rustdoc --test README.md -L target/debug/deps
  - cargo doc --no-deps

notifications:
  email:
on_success: never
