[package]
name = "futures-borrow"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
futures = "0.1"

[dev-dependencies]
futures-test = { version = "0.1", path = "../futures-test" }
